### ISSUE TITLE
fitbudget in Bottomup algorithm

### ISSUE THREAD

**Issue by xuefei-wang** [alchemyst/Segmentation#2]
https://github.com/alchemyst/Segmentation/blob/c00820e135e458c68eef9777b08e3011eaddf984/segment.py#L321

Hi, it seems that the fitbedget parameter does not come into use in the bottom up algorithm, does it?
I guess it's included for the consisteny of algorithm interfaces.
If so, I would suggest leaving out that parameter in the example because it might be a little misleading.
Thanks!

**Comment by xuefei-wang** [comment]
Here they are:

https://github.com/alchemyst/Segmentation/blob/c00820e135e458c68eef9777b08e3011eaddf984/testsegalgorithms.py#L8

https://github.com/alchemyst/Segmentation/blob/c00820e135e458c68eef9777b08e3011eaddf984/testsegmentation.py#L89

Thanks for the great work, it really helps me!

**Comment by alchemyst** [comment]
Ah, thank you. These are actually tests and not examples, but I suppose it's much the same to a user.
